global_frame: 'map'
robot_frame: 'load/base_link'
control_rate: 2.0
geometric_wp_goal_tolerance: 0.5
topological_wp_goal_tolerance: 1.0
plan_next_geometric_path_tolerance: 2

# geometric planner related params
laser_frame: '/rslidar_projected_front'
footprint: [[-0.33, 0.33], [0.33, 0.33], [0.33, -0.33], [-0.33, -0.33]]
wp_goal_tolerance: 1.5
footprint_padding: 0.1
dist_between_wp: 0.5
connector_length: 0.5

# recovery manager related params
recovery_wait_duration: 2.0
recovery_motion_duration: 2.0
recovery_vel: 0.1
