nodes:
- area_name: BRSU_C_L0_C9
  area_type: corridor
  id: 1353
  x: 58.83
  y: 31.82
- area_name: BRSU_C_L0_RoomC022
  area_type: room
  id: 1341
  x: 59.43
  y: 28.7
- area_name: BRSU_C_L0_RoomC025
  area_type: room
  id: 1342
  x: 60.36
  y: 36.77
- area_name: BRSU_C_L0_C8
  area_type: junction
  id: 1354
  x: 51.98
  y: 32.59
- area_name: BRSU_C_L0_C10
  area_type: corridor
  id: 1352
  x: 53.41
  y: 27.16
- area_name: BRSU_C_L0_C15
  area_type: junction
  id: 1346
  x: 43.59
  y: 67.3
- area_name: BRSU_C_L0_C16
  area_type: corridor
  id: 1340
  x: 42.38
  y: 72.54
- area_name: BRSU_C_L0_C17
  area_type: corridor
  id: 1345
  x: 47.28
  y: 67.13
- area_name: BRSU_C_L0_C18
  area_type: corridor
  id: 1344
  x: 51.36
  y: 67.25
- area_name: BRSU_C_L0_RoomC069
  area_type: room
  id: 1314
  x: 51.24
  y: 73.29
- area_name: BRSU_C_L0_C19
  area_type: corridor
  id: 1339
  x: 41.39
  y: 67.33
- area_name: BRSU_C_L0_C20
  area_type: corridor
  id: 1337
  x: 37.77
  y: 67.44
- area_name: BRSU_C_L0_C21
  area_type: corridor
  id: 1336
  x: 28.32
  y: 67.64
- area_name: BRSU_C_L0_C22
  area_type: corridor
  id: 1335
  x: 15.29
  y: 67.98
- area_name: BRSU_C_L0_C23
  area_type: corridor
  id: 1333
  x: 6.95
  y: 68.13
- area_name: BRSU_C_L0_C24
  area_type: junction
  id: 1332
  x: 2.67
  y: 68.3
- area_name: BRSU_C_L0_C25
  area_type: corridor
  id: 1322
  x: 2.94
  y: 73.46
- area_name: BRSU_C_L0_C26
  area_type: corridor
  id: 1331
  x: 2.71
  y: 63.38
- area_name: BRSU_C_L0_A20
  area_type: area
  id: 1330
  x: 2.75
  y: 58.12
- area_name: BRSU_C_L0_A18
  area_type: area
  id: 1329
  x: -0.84
  y: 58.35
- area_name: BRSU_C_L0_A16
  area_type: area
  id: 1328
  x: -0.81
  y: 51.12
- area_name: BRSU_C_L0_A14
  area_type: area
  id: 1327
  x: -1.34
  y: 43.98
- area_name: BRSU_C_L0_A13
  area_type: area
  id: 1326
  x: 2.43
  y: 43.84
- area_name: BRSU_C_L0_A15
  area_type: area
  id: 1325
  x: 6.52
  y: 43.75
- area_name: BRSU_C_L0_A17
  area_type: area
  id: 1324
  x: 6.24
  y: 51.07
- area_name: BRSU_C_L0_A19
  area_type: area
  id: 1323
  x: 6.81
  y: 58.28
- area_name: BRSU_C_L0_C2
  area_type: junction
  id: 1362
  x: 1.8
  y: 33.8
- area_name: BRSU_C_L0_C3
  area_type: corridor
  id: 1360
  x: 2.01
  y: 38.57
- area_name: BRSU_C_L0_C4
  area_type: corridor
  id: 1361
  x: 6.16
  y: 33.65
- area_name: BRSU_C_L0_C5
  area_type: corridor
  id: 1358
  x: 16.21
  y: 33.41
- area_name: BRSU_C_L0_C6
  area_type: corridor
  id: 1357
  x: 31.61
  y: 32.99
- area_name: BRSU_C_L0_C7
  area_type: corridor
  id: 1355
  x: 45.47
  y: 32.66
- area_name: BRSU_A_L0_A4
  area_type: junction
  id: 1312
  x: 1.88
  y: 21.41
- area_name: BRSU_C_L0_C1
  area_type: corridor
  id: 1363
  x: 1.89
  y: 28.3
- area_name: BRSU_A_L0_A3
  area_type: area
  id: 1311
  x: 1.47
  y: 13.46
- area_name: BRSU_C_L0_A3_Door1
  area_type: door
  id: 1304
  x: 3.88
  y: 13.42
- area_name: BRSU_A_L0_A2
  area_type: area
  id: 1310
  x: 1.32
  y: 7.46
- area_name: BRSU_A_L0_A1
  area_type: area
  id: 1309
  x: 0.87
  y: 3.39
- area_name: BRSU_A_E1
  area_type: elevator
  id: 1307
  x: 0.0
  y: 0.0
- area_name: BRSU_A_L0_A8
  area_type: area
  id: 3207
  x: -4.87
  y: 5.48
- area_name: BRSU_A_L0_A12
  area_type: junction
  id: 3206
  x: -12.24
  y: 3.49
- area_name: BRSU_A_L0_C1
  area_type: corridor
  id: 3205
  x: -26.61
  y: 4.04
- area_name: BRSU_A_L0_C2
  area_type: corridor
  id: 3204
  x: -41.66
  y: 3.85
- area_name: BRSU_A_L0_C4
  area_type: corridor
  id: 3203
  x: -54.12
  y: 4.15
- area_name: BRSU_A_L0_C6
  area_type: junction
  id: 3202
  x: -67.13
  y: 4.55
- area_name: BRSU_A_L0_C7
  area_type: corridor
  id: 3201
  x: -79.1
  y: 4.89
- area_name: BRSU_A_L0_C8
  area_type: corridor
  id: 3200
  x: -89.91
  y: 5.3
- area_name: BRSU_A_L0_C9
  area_type: junction
  id: 3199
  x: -98.53
  y: 5.47
- area_name: BRSU_A_L0_C10
  area_type: corridor
  id: 3198
  x: -104.53
  y: 5.74
- area_name: BRSU_A_L0_A10
  area_type: area
  id: 3196
  x: -4.54
  y: 21.06
- area_name: BRSU_A_L0_A13
  area_type: area
  id: 3195
  x: -11.87
  y: 16.36
- area_name: BRSU_A_L0_A9
  area_type: area
  id: 3197
  x: -3.45
  y: 13.39
{connections: [[1353, 1341], [1353, 1342], [1354, 1353], [1354, 1352], [1346, 1340],
    [1346, 1345], [1345, 1344], [1344, 1314], [1346, 1339], [1339, 1337], [1337, 1336],
    [1336, 1335], [1335, 1333], [1333, 1332], [1332, 1322], [1332, 1331], [1331, 1330],
    [1330, 1329], [1329, 1328], [1328, 1327], [1327, 1326], [1326, 1325], [1325, 1324],
    [1324, 1323], [1323, 1330], [1362, 1360], [1360, 1326], [1362, 1361], [1361, 1358],
    [1358, 1357], [1357, 1355], [1355, 1354], [1312, 1363], [1363, 1362], [1311, 1312],
    [1311, 1304], [1310, 1311], [1309, 1310], [1307, 1309], [1310, 3207], [3207, 3206],
    [3206, 3205], [3205, 3204], [3204, 3203], [3203, 3202], [3202, 3201], [3201, 3200],
    [3200, 3199], [3199, 3198], [1312, 3196], [3196, 3195], [3195, 3206], [1309, 3207],
    [3207, 3197], [3197, 1311]]}
