footprint: [[-0.33, 0.33], [0.33, 0.33], [0.33, -0.33], [-0.33, -0.33]]

# obstacle layer
observation_sources: laser_scan_sensor
laser_scan_sensor:
    sensor_frame: /load/front_laser_link
    data_type: LaserScan
    topic: /load/scan
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
    obstacle_range: 8.0
    raytrace_range: 10.0
