global_frame: /map
robot_base_frame: /load/base_link
update_frequency: 1.0
publish_frequency: 1.0
static_map: true
rolling_window: false
resolution: 0.1
transform_tolerance: 0.3
always_send_full_costmap: false

# inflation layer
inflation_radius: 0.5
