global_frame: /load/base_link
robot_base_frame: /load/base_link
update_frequency: 5.0
publish_frequency: 5.0
static_map: false
rolling_window: true
width: 4.0
height: 2.0
resolution: 0.1
map_type: costmap
track_unknown_space: true
transform_tolerance: 0.3
always_send_full_costmap: true

# inflation layer
inflation_radius: 0.5
